apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Naphee25/gitops-nodejs-k8s
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
